package pageUIs.nopCommerce;

public class MyAccountPageUI {
	public static final String CUSTOMER_PAGE_TITLE = "//div[@class='page-title']/h1[text()='My account - Customer info']";
	public static final String CUSTOMER_EMAIL_TEXTBOX = "//input[@id='Email']";
	public static final String CUSTOMER_GENDER_FEMALE_RADIO = "//input[@id='gender-female']";
	public static final String CUSTOMER_FIRSTNAME_TEXTBOX = "//input[@id='FirstName']";
	public static final String CUSTOMER_LASTNAME_TEXTBOX = "//input[@id='LastName']";
	public static final String CUSTOMER_COMPANY_NAME_TEXTBOX = "//input[@id='Company']";
	public static final String CUSTOMER_BIRTHDAY_DROPDOWN = "//select[@name='DateOfBirthDay']";
	public static final String CUSTOMER_BIRTHMONTH_DROPDOWN = "//select[@name='DateOfBirthMonth']";
	public static final String CUSTOMER_BIRTHYEAR_DROPDOWN = "//select[@name='DateOfBirthYear']";
	public static final String CUSTOMER_SAVE_BUTTON = "//button[@id='save-info-button']";

	public static final String ADDRESSES_MENU_LINK = "//li[contains(@class,'customer-addresses')]/a";
	public static final String ADDRESSES_PAGE_TITLE = "//div[@class='page-title']/h1[text()='My account - Addresses']";
	public static final String ADDRESSES_ADD_NEW_BUTTON = "//button[contains(@class,'add-address-button')]";
	public static final String ADDRESSES_FIRSTNAME_TEXTBOX = "//input[@id='Address_FirstName']";
	public static final String ADDRESSES_LASTNAME_TEXTBOX = "//input[@id='Address_LastName']";
	public static final String ADDRESSES_EMAIL_TEXTBOX = "//input[@id='Address_Email']";
	public static final String ADDRESSES_COMPANY_TEXTBOX = "//input[@id='Address_Company']";
	public static final String ADDRESSES_COUNTRY_DROPDOWN = "//select[@id='Address_CountryId']";
	public static final String ADDRESSES_STATE_PROVINCE_DROPDOWN = "//select[@id='Address_StateProvinceId']";
	public static final String ADDRESSES_CITY_TEXTBOX = "//input[@id='Address_City']";
	public static final String ADDRESSES_ADDRESS_1_TEXTBOX = "//input[@id='Address_Address1']";
	public static final String ADDRESSES_ADDRESS_2_TEXTBOX = "//input[@id='Address_Address2']";
	public static final String ADDRESSES_ZIP_POSTALCODE_TEXTBOX = "//input[@id='Address_ZipPostalCode']";
	public static final String ADDRESSES_PHONE_NUMBER_TEXTBOX = "//input[@id='Address_PhoneNumber']";
	public static final String ADDRESSES_FAX_NUMBER_TEXTBOX = "//input[@id='Address_FaxNumber']";
	public static final String ADDRESSES_SAVE_BUTTON = "//button[contains(@class,'save-address-button')]";
	public static final String ADDRESSES_FULLNAME_TEXT = "//li[@class='name']";
	public static final String ADDRESSES_EMAIL_TEXT = "//li[@class='email']";
	public static final String ADDRESSES_PHONE_TEXT = "//li[@class='phone']";
	public static final String ADDRESSES_FAX_TEXT = "//li[@class='fax']";
	public static final String ADDRESSES_COMPANY_NAME_TEXT = "//li[@class='company']";
	public static final String ADDRESSES_ADDRESS1_TEXT = "//li[@class='address1']";
	public static final String ADDRESSES_ADDRESS2_TEXT = "//li[@class='address2']";
	public static final String ADDRESSES_CITY_STATE_ZIP_TEXT = "//li[@class='city-state-zip']";
	public static final String ADDRESSES_COUNTRY_TEXT = "//li[@class='country']";

	public static final String CHANGE_PASSWORD_MENU_LINK = "//li[contains(@class,'change-password')]/a";
	public static final String CHANGE_PASSWORD_PAGE_TITLE = "//div[@class='page-title']/h1[text()='My account - Change password']";
	public static final String CHANGE_PASSWORD_OLD_PASSWORD_TEXTBOX = "//input[@id='OldPassword']";
	public static final String CHANGE_PASSWORD_NEW_PASSWORD_TEXTBOX = "//input[@id='NewPassword']";
	public static final String CHANGE_PASSWORD_CONFIRM_PASSWORD_TEXTBOX = "//input[@id='ConfirmNewPassword']";
	public static final String CHANGE_PASSWORD_CHANGE_PASSWORD_BUTTON = "//button[contains(@class,'change-password-button')]";
	public static final String CHANGE_PASSWORD_NOTIFICATION_BAR = "//div[@id='bar-notification']//p";
	public static final String CHANGE_PASSWORD_NOTIFICATION_BAR_CLOSE_BUTTON = "//div[@id='bar-notification']//span[@class='close']";

	public static final String MY_PRODUCT_REVIEWS_MENU_LINK = "//li[contains(@class,'customer-reviews')]/a";
	public static final String MY_PRODUCT_REVIEWS_PAGE_TITLE = "//div[@class='page-title']/h1[text()='My account - My product reviews']";
	public static final String MY_PRODUCT_REVIEWS_REVIEW_TEXT = "//div[@class='review-text']";

	public static final String ORDERS_MENU_LINK = "//li[contains(@class,'orders')]/a";
	public static final String ORDERS_ORDER_ITEM_TITLE = "//div[contains(@class,'order-item')]//strong";
	public static final String ORDERS_ORDER_DETAIL_BUTTON = "//div[contains(@class,'order-item')]//button";
	public static final String ORDERS_ORDER_OVERVIEW_TEXT = "//div[@class='order-number']";
	public static final String ORDERS_ORDER_DATE_TEXT = "//li[@class='order-date']";
	public static final String ORDERS_ORDER_STATUS_TEXT = "//li[@class='order-status']";
	public static final String ORDERS_ORDER_TOTAL_OVERVIEW_TEXT = "//li[@class='order-total']";
	public static final String ORDERS_BILLING_NAME_TEXT = "//div[@class='billing-info']//li[@class='name']";
	public static final String ORDERS_BILLING_EMAIL_TEXT = "//div[@class='billing-info']//li[@class='email']";
	public static final String ORDERS_BILLING_PHONE_TEXT = "//div[@class='billing-info']//li[@class='phone']";
	public static final String ORDERS_BILLING_FAX_TEXT = "//div[@class='billing-info']//li[@class='fax']";
	public static final String ORDERS_BILLING_COMPANY_TEXT = "//div[@class='billing-info']//li[@class='company']";
	public static final String ORDERS_BILLING_ADDRESS_1_TEXT = "//div[@class='billing-info']//li[@class='address1']";
	public static final String ORDERS_BILLING_CITY_STATE_ZIP_TEXT = "//div[@class='billing-info']//li[@class='city-state-zip']";
	public static final String ORDERS_BILLING_COUNTRY_TEXT = "//div[@class='billing-info']//li[@class='country']";
	public static final String ORDERS_PAYMENT_METHOD_TEXT = "//li[@class='payment-method']/span[@class='value']";
	public static final String ORDERS_PAYMENT_STATUS_TEXT = "//li[@class='payment-method-status']/span[@class='value']";
	public static final String ORDERS_SHIPPING_NAME_TEXT = "//div[@class='shipping-info']//li[@class='name']";
	public static final String ORDERS_SHIPPING_EMAIL_TEXT = "//div[@class='shipping-info']//li[@class='email']";
	public static final String ORDERS_SHIPPING_PHONE_TEXT = "//div[@class='shipping-info']//li[@class='phone']";
	public static final String ORDERS_SHIPPING_FAX_TEXT = "//div[@class='shipping-info']//li[@class='fax']";
	public static final String ORDERS_SHIPPING_COMPANY_TEXT = "//div[@class='shipping-info']//li[@class='company']";
	public static final String ORDERS_SHIPPING_ADDRESS_1_TEXT = "//div[@class='shipping-info']//li[@class='address1']";
	public static final String ORDERS_SHIPPING_CITY_STATE_ZIP_TEXT = "//div[@class='shipping-info']//li[@class='city-state-zip']";
	public static final String ORDERS_SHIPPING_COUNTRY_TEXT = "//div[@class='shipping-info']//li[@class='country']";
	public static final String ORDERS_SHIPPING_METHOD_TEXT = "//li[@class='shipping-method']/span[@class='value']";
	public static final String ORDERS_SHIPPING_STATUS_TEXT = "//li[@class='shipping-status']/span[@class='value']";
	public static final String ORDERS_SKU_TEXT = "//span[@class='sku-number']";
	public static final String ORDERS_PRODUCT_NAME_TEXT = "//td[@class='product']//a";
	public static final String ORDERS_UNIT_PRICE_TEXT = "//span[@class='product-unit-price']";
	public static final String ORDERS_QUANTITY_TEXT = "//span[@class='product-quantity']";
	public static final String ORDERS_SUB_TOTAL_TEXT = "//span[@class='product-subtotal']";
	public static final String ORDERS_CART_OPTION_TEXT = "//div[@class='selected-checkout-attributes']";
	public static final String ORDERS_ORDER_SUB_TOTAL_TEXT = "//tr[1]//td[@class='cart-total-right']/span";
	public static final String ORDERS_SHIPPING_COST_TEXT = "//tr[2]//td[@class='cart-total-right']/span";
	public static final String ORDERS_TAX_VALUE_TEXT = "//tr[3]//td[@class='cart-total-right']/span";
	public static final String ORDERS_ORDER_TOTAL_TEXT = "//tr[4]//td[@class='cart-total-right']/span";
	public static final String ORDERS_REORDER_BUTTON = "//button[text()='Re-order']";
}